120: Korrigiert OpenAPI-Validierungswarnungen durch operationId
Schulconnex/Schulconnex pull request #196
Opened 2024-09-09 14:46 UTC by aldafu

2024-09-09 14:47 UTC, aldafu commented
fixt #120

2024-09-10 14:32 UTC, bwhdien requested changes

2024-09-10 14:32 UTC, bwhdien commented on src/openapi/paths-personen.yaml
> +  operationId: createPersonendatensatz
createPerson müsste es sein. Es wird immer nur eine Person erstellt. Beim Lesen kommen dann aber die Personenkontexte mit.

2024-09-10 14:32 UTC, bwhdien commented on src/openapi/paths-personen-id.yaml
> +  operationId: deletePersonendatensatzId
deletePerson müsste es sein.

2024-09-10 14:32 UTC, bwhdien commented on src/openapi/paths-personen-id.yaml
> +  operationId: updatePersonendatensatzId
updatePersonId

2024-09-10 14:32 UTC, bwhdien commented on src/openapi/paths-personen-id-personenkontexte.yaml
> +  operationId: readPersonenkontexteId
Kann leicht verwechsel werden mit src/openapi/paths-personenkontexte.yaml

Warum nicht "readPersonIdPersonenkontexte"?

2024-09-10 14:32 UTC, bwhdien commented on src/openapi/paths-organisationen-info.yaml
> +  operationId: readOrganisationen
Gleiche Operation ID wie in src/openapi/paths-organisationen.yaml ? 
Vielleicht besser "readOrganisationenInfo"?

2024-09-10 14:32 UTC, bwhdien commented on src/openapi/paths-organisation-info.yaml
> +  operationId: readOrganisation
Vielleicht besser readOrganisationInfo?

2024-09-10 14:32 UTC, bwhdien commented on src/openapi/paths-gruppen-id.yaml
> +  operationId: getGruppeId
readGruppeId

2024-09-10 14:32 UTC, bwhdien commented on src/openapi/paths-gruppen-id-gruppenzugehoerigkeiten.yaml
> +  operationId: getGruppenzugehoerigkeiten
Verdoppelt src/openapi/paths-gruppenzugehoerigkeiten.yaml ? 

Vielleicht besser readGruppeIdGruppenzugehoerigkeiten?

2024-09-10 14:32 UTC, bwhdien commented on src/openapi/paths-gruppen-id-gruppenzugehoerigkeiten.yaml
> +  operationId: createGruppenzugehoerigkeit
Oder createGruppeIdGruppenzugehoerigkeit

2024-09-10 14:32 UTC, bwhdien commented on src/openapi/api-qs.yaml
> +    description: Gibt Rolle an
Rolle und Schule bzw. Organisation

2024-09-10 14:32 UTC, bwhdien commented on src/openapi/api-qs.yaml
> +    description: Beziehung zwischen Personen
zwischen Personenkontexten

2024-09-11 06:57 UTC, aldafu commented on src/openapi/paths-gruppen-id-gruppenzugehoerigkeiten.yaml
> +  operationId: createGruppenzugehoerigkeit
Grundlage ist immer der Name des Datenmodells, nicht der Pfad des Endpunkts. Da es keine weitere Möglichkeit gibt eine Gruppenzugehörigkeit zu erstellen, schien ein längerer Methodennamen nicht notwendig. Wenn noch gewünscht, werde ich es ändern.

2024-09-11 07:01 UTC, bwhdien commented
@aldafu Aber wir hatten es letzten Freitag anders besprochen, siehe die Beispiele im Ticket

2024-09-11 07:02 UTC, aldafu commented on src/openapi/paths-organisation-info.yaml
> +  operationId: readOrganisation
Grundlage ist immer der Name des Datenmodells, nicht der Pfad des Endpunkts. Verwechslung mit QS-API scheint mir ausgeschlossen, da es eine andere API ist. Wenn gewünscht, werde ich es ändern.

2024-09-11 07:02 UTC, aldafu commented on src/openapi/paths-organisationen-info.yaml
> +  operationId: readOrganisationen
Grundlage ist immer der Name des Datenmodells, nicht der Pfad des Endpunkts. Verwechslung mit QS-API scheint mir ausgeschlossen, da es eine andere API ist. Wenn gewünscht, werde ich es ändern.

2024-09-11 07:37 UTC, aldafu commented
> @aldafu Warum schlägt der Deployment-Test fehl?

Die Dateinamen der generierten Markdown-API-Dateien nutzen jetzt die `operationId`, haben sich also geändert. Für die Dienste-API waren noch die "alten" Dateinamen manuel in `sidebar.ts` referenziert und wurden dann daher nicht mehr gefunden. Als Korrektur werden jetzt die Dateinamen dynamisch in `sidebar.ts` referenziert.

> @aldafu Aber wir hatten es letzten Freitag anders besprochen, siehe die Beispiele im Ticket.
Weiterer Komm. im Ticket (inhaltliche Diss.)

Ist jetzt für die beanstandeten Stellen aktualisiert.

Ist auch gewünscht das konsequent für alle Endpunkte zu tun, zB auch das im Ticket genannte `createPersonkontexteIdSichtfreigaben`?

2024-09-11 08:07 UTC, bwhdien commented
@aldafu Nächsten Freitag (13.9.) im Team besprechen?

2024-09-11 09:20 UTC, aldafu commented
> @aldafu Dann muss dieser PR vor #193 gemergt werden und #193 braucht danach einen Rebase, richtig?

Wäre wahrscheinlich günstig, ja

2024-09-13 10:22 UTC, bwhdien approved these changes

2024-09-13 10:36 UTC, bwhdien approved these changes

2024-09-16 10:54 UTC, O-Fischer approved these changes
Keine Ergänzungen.

2024-09-16 10:56 UTC, merged