Erweiterungen
Schulconnex/Schulconnex pull request #197
Opened 2024-09-13 09:08 UTC by ChristianFuhrhop

2024-09-13 14:18 UTC, ChristianFuhrhop commented
Erste Version zu Ticket https://github.com/Schulconnex/Schulconnex/issues/134
"Servereigene Erweiterung der API (Vendor-Extensions) (TFS #4572) #134"

Vereinfachte Version ohne Schema-Attribut mit herstellerspezifischen (oder anwendungsspezifischen) URNs, sowie ein paar Richtlinien zur Verwendung solcher Attribute.

2024-09-18 17:53 UTC, bwhdien requested changes

2024-09-18 17:53 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +Schulconnex ermöglicht es Herstellern, in Absprache mit dem jeweiligen Betreiber eines Schulconnex-Serveres, eigene, anwendungsfallspezifische, Attribute hinzuzufügen.
Erweiterungen können doch ausschließlich Schulconnex-Server anbieten. Ich würde es nicht so darstellen, als ob Hersteller die Serverbetreiber um zusätzliche Attribute bitten können.

2024-09-18 17:53 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +URNs für Zusatz-Attribute müssen das folgende Format haben:
Das ist wohl eine zu große Einschränkung. Wir hatte im Mai bekannt gegeben, dass Vendor-Attribute ein URN-Format haben müssen, mehr nicht. D. h. "urn:<namespace>:<beliebig>", was den IETF-Vorgaben für URNs entspricht. Der Anbieter sollte sich sicher sein, dass er den Namespace beanspruchen kann, in der Regel dadurch, dass er eine entsprechende Internetdomäne kontrolliert.

2024-09-18 17:53 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +Nur `<anbieterkennung>` und `<attributsobjektname>`  können vom Anbieter bestimmt werden. Der Rest der URN ist direkt zu übernehmen.
s.o.

2024-09-18 17:53 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +Anbieterkennung, Attributsobjektname und die Namen der zusätzlichen Attribute müssen den Regeln für Attributsnamen in Schulconnex folgen. Es ist nur Kleinschreibung erlaubt und es sind keine Sonderze
Nur die Einschränkungen, die auch aus  RFC 3986 folgen.

2024-09-18 17:53 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +  "urn:schulsystemix:params:schulconnex:schemas:core:1.0:adresserweiterung" {
Ist das Beispiel geeignet? Adressdaten werden doch in Schulconnex selbst abgebildet. M. E. sollte ein Beispiel verwenden, was sehr speziell ist und offensichtlich kaum Chancen hat, irgendwann einmal in den Standard übernommen zu werden (Personalnummer eines Bundeslandes, Benutzername, Zugangsdaten)

2024-09-18 17:53 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +* Anbieter von anbieterspezifische Attributen sind dazu verpflichtet die geltenden IT-Sicherheitsrichtlinien zu beachten. So ist es beispielsweise unzulässig ein Attribut `passwortklartext` zu nutzen
Die Verbote würde ich erst einmal weglassen.

2024-09-18 17:53 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +* Inhalte anbieterspezifische Attributen sollen nicht mit Inhalten von Schulconnex Attributen überlappen. Wird beispielsweise bei einer Adresse noch der Strassenname gewünscht, so sollte dieser als A
M. E. dürfen sich nicht überlappen

2024-09-18 17:53 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +  * Wird ein existierendes Standard-Attribute kopiert, so darf dieses nur zur Erkennung von Inkonsistenzen geschehen. Inhaltlich sind immer die Werte der Standard-Attribute zu nutzen.
Verstehe ich nicht ganz

2024-09-19 08:08 UTC, ChristianFuhrhop commented on docs/schnittstellen/vendor-extensions.md
> +Schulconnex ermöglicht es Herstellern, in Absprache mit dem jeweiligen Betreiber eines Schulconnex-Serveres, eigene, anwendungsfallspezifische, Attribute hinzuzufügen.
In der Praxis wird das schwer zu vermeiden sein.
Außer wir erlauben Erweiterungen nur für Quellsysteme.
Wenn ein Anbieter ein Attribut bei einem Datenmodell hinzufügt (beispielsweise bei Gruppe), dann ist sonst unklar wann und unter welchen Bedingungen dieses Attribut an Dienste ausgeliefert werden kann. 
Entweder gehen alle anbieterspezifischen Erweiterungen immer an alle Dienste, was kaum gewünscht sein kann, oder das muss vom Serverbetreiber irgendwie freigeschaltet werden. Dann ist es aber schon so, dass "Hersteller die Serverbetreiber um zusätzliche Attribute bitten" müssen.

2024-09-19 08:43 UTC, ChristianFuhrhop commented on docs/schnittstellen/vendor-extensions.md
> +URNs für Zusatz-Attribute müssen das folgende Format haben:
Eine völlige Freigabe der URN-Struktur halte ich für problematisch, insbesondere, wenn wir in der nächsten Version auf ein 'richtiges' Schemas-Format umsteigen wollen.
Da haben die einzelnen Teil der URN eine Bedeutung und wenn wir da jetzt 'beliebige' URNs erlauben, wie **_URN:anbieter.de:rfc:zeitzone_** dann müssen die in der nächsten Version an die Schema-Struktur angepasst werden. 
Da scheint es sinnvoller die möglichen URNs auf URNs zu beschränken, die auch später Sinn machen. Und das bedeutet, dass die Art der URN (params) einigermaßen strukturiert ist und die sinnvolle Informationen enthält. 
Welche Art der Erweiterung ist es?  :params
Was wird erweitert? :schulconnex
Wonach richtet sich die Erweiterung? :schemas:core:1.0

Durch die Verwendung der Anbieterkennung in der URN kann sich der Anbieter sicher sein, dass er den Namespace kontrollieren kann und den Namen der Erweiterung kann er hinten frei wählen. 
Da sehe ich keine unzumutbare Einschränkung für Hersteller, da es ja nur eine 'Klammer' um die eigenen Attribute darstellt, so dass der Hersteller dort sowieso die eigenen Attributnamen benutzen kann.

Ich sehe keinen wirklichen Vorteil, wenn eine beliebig zusammengesetzte URN erlaubt wird (auch für Anbieter nicht), aber potentiell Probleme, wenn wir auf Schemas umsteigen.

Was man eventuell machen sollte, wäre statt **:schemas:core:1.0** eher **:schemas:core:2.0**, da 1.0 inzwischen deprecated ist. Macht inhaltlich keinen wirklichen Unterschied, sieht aber aktueller aus.

2024-09-19 08:45 UTC, ChristianFuhrhop commented on docs/schnittstellen/vendor-extensions.md
> +Anbieterkennung, Attributsobjektname und die Namen der zusätzlichen Attribute müssen den Regeln für Attributsnamen in Schulconnex folgen. Es ist nur Kleinschreibung erlaubt und es sind keine Sonderze
Wie gesagt: Ja, kann man machen, aber wir machen uns das Leben da schwerer, wenn wir irgendwann auch die Einschränkungen, die aus SCIM folgen mit berücksichtigen wollen.

2024-09-19 08:52 UTC, ChristianFuhrhop commented on docs/schnittstellen/vendor-extensions.md
> +  "urn:schulsystemix:params:schulconnex:schemas:core:1.0:adresserweiterung" {
Ich finde das Beispiel schon aussagekräftig, da in der Adresse eben keine Informationen wie Straße und Hausnummer abgebildet werden. Da ist auch ohne weiteren Kontext erkennbar, was an Informationen hinzu kommt,
Und Adresse ist ein recht einfaches Datenmodell.
 Wenn ich zu Personenkontexten da als Beispiel Zugangsdaten hinzu füge, dann muss ich die Idee dahinter erst erklären und das Beispiel-JSON wird vergleichsweise lang. Und der relevante Teil (die neuen Attribute) gehen dabei etwas unter.
Ich kann gerne ein neues Beispiel machen, glaube aber nicht, dass es die Lesbarkeit und Nutzbarkeit verbessert.

2024-09-19 08:53 UTC, ChristianFuhrhop commented on docs/schnittstellen/vendor-extensions.md
> +* Anbieter von anbieterspezifische Attributen sind dazu verpflichtet die geltenden IT-Sicherheitsrichtlinien zu beachten. So ist es beispielsweise unzulässig ein Attribut `passwortklartext` zu nutzen
Ok.

2024-09-19 08:54 UTC, ChristianFuhrhop commented on docs/schnittstellen/vendor-extensions.md
> +* Inhalte anbieterspezifische Attributen sollen nicht mit Inhalten von Schulconnex Attributen überlappen. Wird beispielsweise bei einer Adresse noch der Strassenname gewünscht, so sollte dieser als A
Dann kann ein Anbieter aber keine Änderungen erkennen. Siehe unten.

2024-09-19 09:01 UTC, ChristianFuhrhop commented on docs/schnittstellen/vendor-extensions.md
> +  * Wird ein existierendes Standard-Attribute kopiert, so darf dieses nur zur Erkennung von Inkonsistenzen geschehen. Inhaltlich sind immer die Werte der Standard-Attribute zu nutzen.
Momentan hat ein Anbieter keine Möglichkeit Änderungen zu erkennen.
Wenn beispielsweise eine andere Anwendung aufgrund eines Umzugs eine Adressänderung von "80469 München" auf "07557 Gera" vornimmt, dann kann es geschehen, dass diese Anwendung die anbieterspezifischen Attribute             "strasse": "Walterweg" und "hausnummer": "5" unverändert lässt und dadurch Inkonsistenzen entstehen, welche nicht zu erkennen sind.  
Wenn der Anbieter in seinem 'eigenen' Attributraum (urn:schulsystemix:params:schulconnex:schemas:core:1.0:adresserweiterung) eine Kopie der Ortsangabe hält  ("80469 München"), so können Anwendungen dieses Anbieters zumindest erkennen, dass ein Umzug stattgefunden hat und reagieren.

2024-09-20 21:05 UTC, bwhdien requested changes

2024-09-20 21:05 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +Schulconnex ermöglicht es Herstellern, in Absprache mit dem jeweiligen Betreiber eines Schulconnex-Serveres, eigene, anwendungsfallspezifische, Attribute hinzuzufügen.
Schulconnex-Servers
anwendungsfallspezifische Attribute (Vendor Extensions)

2024-09-20 21:05 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +        "stammorganisation": "string",
IST: "string"
SOLL: "<irgeneine UUID>"

2024-09-20 21:05 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +Solche Attribute werden innerhalb eines herstellerspezifischen Objektes gekapselt.
Herstellerspezifische Attribute können auch primitive Typen als Wert haben. In dem Beispiel unten ist das ja so. Also doch eher: die Werte von herstellerspezifischen Attributen sind entweder primitive Typen oder h. Objekte.

2024-09-20 21:05 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +Das herstellerspezifische Objekt wird durch einen Uniform Resource Name (URN) (nach [RFC 3986][1]) gekennzeichnet.
Der Name eines herstellerspezifischen Attributs muss ein gültige U. R. N. nach RFC.... sein.

2024-09-20 21:05 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +Hierzu sind die angepasstes Datenmodelle für Diensteanbieter, wo benötigt, um diese Attribute zu erweitern und, analog zu den standardisierten Attributen, die aue auszuliefernde Anzahl und die Notwen
sind das angepasste D. f. D., sofern benötigt, 
die Kardinalität?

Diese Angaben.... -> ist eine Wiederholung

2024-09-20 21:05 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +title: Anbieterspezifische Erweiterungen
Wenn im Text überall von Attributen die Rede ist, sollte hier auch "Anbieterspezifische Attribute" stehen, oder?

2024-09-20 21:05 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +* Anbieter von anbieterspezifische Attributen sind dazu verpflichtet die geltenden IT-Sicherheitsrichtlinien und Datenschutzrichtlinien zu beachten.
IST: sind dazu verpflichtet...
SOLL: das wollten wir doch als Hinweis formulieren mit dem zus. Hinweis, dass die Verantwortung beim Betreiber des Schulconnex-Servers liegt.

2024-09-20 21:05 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +* Inhalte anbieterspezifische Attributen sollen nicht mit Inhalten von Schulconnex Attributen überlappen.
Die Inhalte von .....fischen Attributen sollen .... von regulären Schulconnex-Attributen....

2024-09-20 21:05 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +* Anwendungen, welche anbieterspezifische Attribute nicht kennen, müssen diese beim Update von Datennobjekten unverändert mit angeben.
Schnittstellen-Clients, w..... nicht verarbeiten, ..... Datenbankobjekten .... unverändert mitliefern. Die Regeln für PUT-Operationen gelten auch für anbieterspezifische Attribute.

2024-09-20 21:05 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +* Löscht eine Anwendung ein Datenobjekt oder entfernt in zusammengesetztes Attribut in einem Datenobjekt, so werden dabei auch anbieterspezifische Attribute darin gelöscht. Anwendungen können davon a
entfernt in z. A. i. einem Dateno. -> verstehe ich nicht

2024-09-20 21:05 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +* Es liegt in der Verantwortung der Anwendung, welche ein anbieterspezifisches Attribut einfügt, dass dieses Attribut konsistent mit anderen Angaben ist, fall sich diese ändern. Wird beispielsweise,
falls

2024-09-20 21:05 UTC, bwhdien commented on sidebars.ts
> +        'schnittstellen/vendor-extensions',
Vendor Ext. taucht jetzt nur noch als Dateiname auch, also vllt. eher "anbieterattribute"?

2024-09-23 13:51 UTC, ChristianFuhrhop commented on docs/schnittstellen/vendor-extensions.md
> +Schulconnex ermöglicht es Herstellern, in Absprache mit dem jeweiligen Betreiber eines Schulconnex-Serveres, eigene, anwendungsfallspezifische, Attribute hinzuzufügen.
Fixed.

2024-09-23 13:51 UTC, ChristianFuhrhop commented on docs/schnittstellen/vendor-extensions.md
> +title: Anbieterspezifische Erweiterungen
Fixed.

2024-09-23 13:59 UTC, ChristianFuhrhop commented on docs/schnittstellen/vendor-extensions.md
> +Hierzu sind die angepasstes Datenmodelle für Diensteanbieter, wo benötigt, um diese Attribute zu erweitern und, analog zu den standardisierten Attributen, die aue auszuliefernde Anzahl und die Notwen
Angepasst. Allerdings wird das Wort "Kardinalität"sonst nirgends in der Spezifikation benutzt, daher umgangsprachlich als "wie viele Elemente die Antwort enthalten kann oder muss" beschrieben.

2024-09-23 14:00 UTC, ChristianFuhrhop commented on docs/schnittstellen/vendor-extensions.md
> +        "stammorganisation": "string",
Fixed.

2024-09-23 14:07 UTC, ChristianFuhrhop commented on docs/schnittstellen/vendor-extensions.md
> +* Anbieter von anbieterspezifische Attributen sind dazu verpflichtet die geltenden IT-Sicherheitsrichtlinien und Datenschutzrichtlinien zu beachten.
Ist jetzt so umformuliert. Allerdings halte ich es juristisch weiterhin für riskant, die Verantwortung ausschliesslich beim Server-Betreiber zu verorten. Das kann leicht so interpretiert werden, dass im Schadensfall den Anbieter keine Schuld bei einem Vergehen hat, sondern diese automatisch vom Server-Betreiber übernommen wird. Daher würde ich den zweiten Teil ("Die Verantwortung dafür liegt beim Betreiber des jeweiligen Schulconnex-Servers.") gerne ersatzlos streichen.  Wenn da irgendwas schief gehen sollte, dann sollen das Juristen entscheiden, bei wem die Verantwortung liegt, nicht die Spezifikation.

2024-09-23 14:09 UTC, ChristianFuhrhop commented on docs/schnittstellen/vendor-extensions.md
> +* Inhalte anbieterspezifische Attributen sollen nicht mit Inhalten von Schulconnex Attributen überlappen.
fixed

2024-09-23 14:10 UTC, ChristianFuhrhop commented on docs/schnittstellen/vendor-extensions.md
> +* Anwendungen, welche anbieterspezifische Attribute nicht kennen, müssen diese beim Update von Datennobjekten unverändert mit angeben.
Fixed.

2024-09-23 14:11 UTC, ChristianFuhrhop commented on docs/schnittstellen/vendor-extensions.md
> +* Löscht eine Anwendung ein Datenobjekt oder entfernt in zusammengesetztes Attribut in einem Datenobjekt, so werden dabei auch anbieterspezifische Attribute darin gelöscht. Anwendungen können davon a
Umformuliert.

2024-09-23 14:12 UTC, ChristianFuhrhop commented on docs/schnittstellen/vendor-extensions.md
> +* Es liegt in der Verantwortung der Anwendung, welche ein anbieterspezifisches Attribut einfügt, dass dieses Attribut konsistent mit anderen Angaben ist, fall sich diese ändern. Wird beispielsweise,
Fixed

2024-09-23 14:17 UTC, ChristianFuhrhop commented on sidebars.ts
> +        'schnittstellen/vendor-extensions',
Dem stimme ich zu, aber aktuell bekomme ich Fehlermeldungen, wenn ich diesen Branch ausschecke und mochte daher ungerne kurz vor der Präsentation einen 'blinden' Umbau der Filestruktur vornehmen. Für die Präsentation sollte es auch der alte Filename noch tun.

2024-09-23 14:26 UTC, O-Fischer commented
@ChristianFuhrhop am besten @aldafu als Reviewer hier entfernen oder? Wir wollen das ja heute noch mergen.

2024-09-23 14:29 UTC, ChristianFuhrhop commented
Ok, ist al Reviewer entfernt.

2024-09-23 15:00 UTC, O-Fischer approved these changes
Keine weiteren Anmerkungen.

2024-09-23 16:16 UTC, bwhdien approved these changes

2024-09-23 16:17 UTC, merged