Änderungen seit Version 1.4
Schulconnex/Schulconnex pull request #202
Opened 2024-09-17 09:35 UTC by ChristianFuhrhop

Erste Version des Anhangs

2024-09-17 15:28 UTC, ChristianFuhrhop commented
Die GitHub Issues wollte ich hier genau nicht nutzen. 
Wer jede Änderungen im Detail nachlesen will, der kann das ja tun, aber in vielen Fällen gingen Sachen ja hin und her. Und wenn dann jemand was von "Sichtfreigaben von Gruppen" oder der initial viel komplexeren Sichtfreigabe API liest, dann verwirrt das mehr. Und Dinge wie "Das wurde in der englischen Version nachgetragen" brauchen die meisten Nutzer auch nicht.
Ziel ist eher den Leuten, welche mit der API arbeiten einen Überblick zu geben, worauf sie eventuell achten müssen und was zusätzlich genutzt werden kann/muss/sollte. 
Für mich ist das eher wie das "Änderungen von v1.3 auf v1.4" Dokument. Das hat auch nur die wichtigsten Punkte aufgegriffen. Für eine vollständige Übersicht gab es damals die kleinteilige Liste hinten am PDF, wo eben auch viele Sachen wie "Kommafehler korrigiert", "Namen vereinheitlicht", "Links angepasst" drin standen, welche für die Arbeit mit der Spezifikation zu kleinteilig sind.
Daher möchte ich auch hier eine 1:1 Beziehung zu Issues oder Commits vermeiden.

2024-09-20 15:01 UTC, ChristianFuhrhop commented
Neue Kategorie "Versionshistorie" in den Sidebar eingefügt, dazu kurzer Einstiegsseite und Updates seit V1.4. Untermenu schafft Raum für zukünftige Beschreibungen von Änderungen.

2024-09-20 21:14 UTC, bwhdien requested changes
Ich würde die gesamte Änderungshistorie in eine Seite setzen, wie heute besprochen. 
M. E. sollten die Änderungseinträge zwar knapp, aber doch so ausführlich sein, dass die Funktion oder Erweiterung klar ist.

2024-09-20 21:14 UTC, bwhdien commented on docs/versionshistorie/aenderungen-1-5.md
> +  * GET /organisation-info
Der Endp. ist nicht neu. 
Ist GET /organisationen-info in der Dienste API gemeint?

2024-09-20 21:14 UTC, bwhdien commented on docs/versionshistorie/aenderungen-1-5.md
> +# Änderungen seit Version 1.4
von 1.4 zu 1.5

2024-09-20 21:14 UTC, bwhdien commented on docs/versionshistorie/aenderungen-1-5.md
> +* Anbieter können auch eigene Attribute hinzufügen
Regelungen für herstellereigene Attribute

2024-09-23 06:43 UTC, ChristianFuhrhop commented
Gewünschte Anpassungen vorgenommen.
Versionshistorie auf einer Seite, organisation-info nur bei Diensten eine neue API, herstellereigene Attribute werden erwähnt.

2024-09-30 07:42 UTC, bwhdien commented
@ChristianFuhrhop Dann wird dieser zugunsten von #215 geschlossen (ohne Merge)?

2024-09-30 07:45 UTC, ChristianFuhrhop commented
Dieser hier ist einfach falsch zugeordnet und kann weg.

2024-09-30 10:49 UTC, bwhdien approved these changes

2024-09-30 10:52 UTC, closed without merging