Versionhistorie https://github.com/Schulconnex/Schulconnex/issues/201
Schulconnex/Schulconnex pull request #215
Opened 2024-09-27 13:28 UTC by ChristianFuhrhop

Neue Version, um den Pull Request diesmal korrekt auf develop statt auf main zu machen.

Initaler Push zur Versionshistorie war versehentlich auf den 'main' Branch.

Modifikationen jetzt auf 'develop' als Pull-Request.

2024-09-30 07:13 UTC, bwhdien commented
@ChristianFuhrhop Warum wurde dieser PR angelegt? Was ist der Unterschied zu #202

2024-09-30 07:35 UTC, ChristianFuhrhop commented
Der andere Pull-Request war versehentlich auf dem "Main" Branch.
Daher wurde der identische Inhalt noch mal als Pull-Request auf "Develop" erstellt.

2024-09-30 10:53 UTC, bwhdien approved these changes

2024-10-02 09:47 UTC, AnnikaStrupp-initAG requested changes

2024-10-02 09:47 UTC, AnnikaStrupp-initAG commented on docs/versionshistorie.md
> +### Neue Datenmodell und APIs
Tippfehler Zeile 13: Neue Datenmodelle ...

2024-10-02 09:47 UTC, AnnikaStrupp-initAG commented on docs/versionshistorie.md
> +* Codeliste Rollen: Neue Rollen `SchB` (Schulbetreuung) und `NLehr` (Nichtlehrendes Personal) definiert
Zeile 31: ist `SchB` "Schulbetreuung" oder "Schulbegleitung"?

2024-10-02 09:47 UTC, AnnikaStrupp-initAG commented on docs/versionshistorie.md
> +* Die Codeliste Gruppenoptionen enthält derzeit keine Werte.
Interpunktion Aufzählung: einige der Aufzählungsglieder enden mit Schlusszeichen (Punkt), andere nicht.

2024-10-02 10:23 UTC, bwhdien approved these changes

2024-10-02 12:08 UTC, merged