219 Finale Redaktion der Seite über herstellereigene Attribute
Schulconnex/Schulconnex pull request #221
Opened 2024-09-30 12:33 UTC by bwhdien

2024-09-30 13:12 UTC, ChristianFuhrhop submitted a review, later dismissed

2024-10-02 07:20 UTC, AnnikaStrupp-initAG requested changes

2024-10-02 07:20 UTC, AnnikaStrupp-initAG commented on docs/schnittstellen/vendor-extensions.md
> +Im folgenden Beispiel wird der Datensatz einer Person um das herstellereigene Attribut "Personalnummer" dieser Person bei der Stammorganisation erweitert. `schulsystemix` ist hierbei der Name eines f
Zeile 21: Attribut  `personalnummer`

2024-10-02 07:20 UTC, AnnikaStrupp-initAG commented on docs/schnittstellen/vendor-extensions.md
> +Im folgenden Beispiel wird der Datensatz einer Person um das herstellereigene Attribut "Personalnummer" dieser Person bei der Stammorganisation erweitert. `schulsystemix` ist hierbei der Name eines f
Keine weiteren Anmerkungen.

2024-10-02 08:20 UTC, bwhdien commented on docs/schnittstellen/vendor-extensions.md
> +Im folgenden Beispiel wird der Datensatz einer Person um das herstellereigene Attribut "Personalnummer" dieser Person bei der Stammorganisation erweitert. `schulsystemix` ist hierbei der Name eines f
@AnnikaStrupp-initAG Korrigiert

2024-10-02 08:25 UTC, AnnikaStrupp-initAG approved these changes

2024-10-02 08:29 UTC, ChristianFuhrhop approved these changes

2024-10-02 08:36 UTC, merged