Schnelleinstieg für Entwickler #243
Schulconnex/Schulconnex pull request #254
Opened 2024-11-26 14:24 UTC by ChristianFuhrhop

Erstes Commit der Texte für Dienste und Quellsysteme. Derzeit noch ohne Links, da sich die Gesamtstruktur noch verändern wird.

In der 'alten' Dokumentstruktur sind die beiden Seiten noch 'hintereinander' angeordnet.
Wenn wir die neue Version haben (wo Dienste- und Quellsystem-API stark getrennt sind), wird jeder 'Zweig' nur eine der beiden Seiten haben.

Wenn die neue Struktur stabil ist, macht es Sinn die wichtigsten Seiten (Datenmodelle, Fehlercodes, Codelisten, English Notes) noch zu verlinken. Aber das macht erst Sinn nach der Umstellung.

2024-11-28 14:35 UTC, aldafu approved these changes
lgtm

2024-12-18 10:49 UTC, gorkemg commented
@bwhdien bitte einmal reviewen.

2024-12-18 11:30 UTC, bwhdien requested changes
Die redundante Textteile, die für beide APIs gelten, sollten ausgelagert werden.

2024-12-18 11:30 UTC, bwhdien commented on docs/schnelleinstieg-dienste.md
> +Die Dienste-API dient primär der Bereitstellung von Anmeldeinformationen der Bereitstellung von zur Anmeldung von Nutzern an externe Dienste. Die Dienste API stellt nur einen lesenden Zugriff auf Inf
Bereitstellung doppelt

2024-12-18 11:30 UTC, bwhdien commented on docs/schnelleinstieg-dienste.md
> +Der Abschnitt API-Autorisierung und Authentifikation bei Dienstanbietern beschreibt die Nutzung der REST-API zum Zugriff auf die Informationen, sowie die Möglichkeit Anmeldeinformationen teilweise au
Möglichkeit,

2024-12-18 11:30 UTC, bwhdien commented on docs/schnelleinstieg-dienste.md
> +Viele der verwendeten Attribute können nur Werte aus fest definierten Codelisten annehmen. Diese sind im Kapitel Codelisten spezifiziert.
Gilt für beide API, ebenso der Komm. zu den engl. API notes

2024-12-20 15:17 UTC, bwhdien requested changes

2024-12-20 15:17 UTC, bwhdien commented on docs/schnelleinstieg.md
> +---
Der Header

---
title: ''
---

müsste doch in die nicht zu importieren Teile, oder?

2024-12-20 15:25 UTC, bwhdien requested changes

2024-12-20 15:25 UTC, bwhdien commented on docs/schnelleinstieg-qs.md
> +Das Kapitel zur Nutzung der [REST-API](schnittstellen/schnittstellen-qs), erläutert allgemein den Zugriff
Kein , vor erläutert

2024-12-20 15:25 UTC, bwhdien commented on docs/schnelleinstieg-qs.md
> +auf Resourcen, die Schulconnex-spezifischen Fehlercodes und den Validierungsprozess bei Anfragen an die REST-API,
REST-API sowie den Auto.....

2024-12-20 15:25 UTC, bwhdien commented on docs/schnelleinstieg-qs.md
> +Ein nicht-normativer [Praxisleitfaden](praxisleitfaden) für die Implementierung beschreibt exemplarisch
nicht normative oder nichtnormativer

2024-12-20 15:25 UTC, bwhdien commented on docs/schnelleinstieg-dienste.md
> +vertraglich welche der definierten Attribute für den Betrieb des Dienstes notwendig sind. Zur Wahrung des
vertraglich, welche

2024-12-20 15:25 UTC, bwhdien commented on docs/schnelleinstieg.md
> +Die Dienste-API dient primär der Bereitstellung von Anmeldeinformationen zur Anmeldung von Nutzern an externe
Anmeldeinformationen -> in anderen Zusammenhängen haben wir von Kontextinformationen gesprochen.

2024-12-20 15:25 UTC, bwhdien commented on docs/schnelleinstieg.md
> +sowohl als Webseite als auch als herunterladbare Spezifikation im YAML-Format zur Verfügung.
als auch zum Download im YAML-Format......

2024-12-20 15:35 UTC, aldafu commented on docs/schnelleinstieg.md
> +---
Das passt so wie es ist. Der importierte Text wird mit jeweils anderem Titel in den anderen beiden Dateien genutzt. Daher ist hier der Titel "leer" gesetzt.

2024-12-20 15:36 UTC, aldafu approved these changes

2024-12-20 15:40 UTC, bwhdien approved these changes

2024-12-20 15:40 UTC, merged