Trenne Dienste- und QS-API
Schulconnex/Schulconnex pull request #259
Opened 2024-11-27 15:44 UTC by aldafu

Draft-PR für #236

2024-11-28 11:01 UTC, ChristianFuhrhop approved these changes

2024-12-03 11:59 UTC, bwhdien commented
@aldafu Warum sind mache Dateien mdx und manche md?

2024-12-12 11:40 UTC, bwhdien requested changes
Vorschläge
* In der oberen Menübar "Allgemeines" statt "Einleitung"
* Kapitel Allgmeines müsste nach Diensten und Quellsytemen getrennt werden
* Das gleiche für die Praxisleitfäden
* OIDC-Claims nach Dienste
* Anbieterspez. Attri. nach Allgemeines
* Autorisierung Quellsysteme nach Quellsysteme
* Codelisten, Glossar, English Notes, Versionshistorie in "Allgemeines" (jetzt "Einleitung")

2024-12-12 16:40 UTC, aldafu commented
Rebase ist hiermit verfügbar. Auch die aktuellen Vorschläge wurden berücksichtigt. Bis auf:

>     * Anbieterspez. Attri. nach Allgemeines
> 

Der Punkt ist aktuell nur in der Dienste-API verlinkt. Reicht das so, oder müsste das korrigiert werden?

2024-12-13 07:21 UTC, bwhdien commented
Ein paar Abschnitte müssen aus "Dienste" und "Quellsysteme" wohl noch entfernt werden, z. B.
* Dienste -> Synchronisation Quellsysteme
* Dienste -> Ablauf Schuljahreswechsel
Bei Quellsysteme fehlt Erweiterungen -> Anbieterspezifizische Attribute
M. E. sollte Anbieterspez. Attr. auch unter Allgemeines verfügbar sein.

2024-12-13 13:08 UTC, aldafu commented
> Ein paar Abschnitte müssen aus "Dienste" und "Quellsysteme" wohl noch entfernt werden, z. B.
> 
>     * Dienste -> Synchronisation Quellsysteme
> 
>     * Dienste -> Ablauf Schuljahreswechsel
>       Bei Quellsysteme fehlt Erweiterungen -> Anbieterspezifizische Attribute
>       M. E. sollte Anbieterspez. Attr. auch unter Allgemeines verfügbar sein.

Alle Punkte sind mit den letzten Änderungen berücksichtigt.

2024-12-13 13:15 UTC, gorkemg approved these changes
Sieht für mich gut aus.

2024-12-13 13:27 UTC, bwhdien commented
@gorkemg  Wurde noch einmal geprüft, dass keine Texte im Vergleich zur aktuell deployten Version verloren gegangen sind?

2024-12-13 13:29 UTC, gorkemg commented
> @gorkemg Wurde noch einmal geprüft, dass keine Texte im Vergleich zur aktuell deployten Version verloren gegangen sind?
Ja genau. Ich bin alle Seiten durchgegangen und bin auch auf 1-2 kleine Sachen gestoßen, die Alex netterweise direkt verbessert hat, siehe letzten Commit zum Beispiel.

2024-12-13 18:32 UTC, bwhdien requested changes
@gorkemg @aldafu Unter Quellsysteme ist jetzt noch Versionshistorie, unter Dienste aber nicht. M. E. reicht es, wenn sie unter Allgemeine ist.

2024-12-16 15:25 UTC, gorkemg submitted a review, later dismissed

2024-12-16 21:50 UTC, bwhdien commented
@aldafu @gorkemg Vmtl. wg. #272 haben wir jetzt Merge-Konflikte

2024-12-17 09:40 UTC, aldafu commented
> @aldafu @gorkemg Vmtl. wg. #272 haben wir jetzt Merge-Konflikte

Hab soeben nochmal einen Rebase gemacht, keine Merge-Konflikte mehr.

2024-12-17 09:45 UTC, bwhdien approved these changes

2024-12-17 09:46 UTC, gorkemg approved these changes

2024-12-17 09:48 UTC, ChristianFuhrhop approved these changes

2024-12-17 09:52 UTC, merged