All examples added in semantik
Schulconnex/Schulconnex pull request #265
Opened 2024-12-03 11:51 UTC by TheAnhNguyenFOKUSFAME

Hier sind die Beispiele aufgelistet, die innerhalb der Diskussionen der letzten Monate entstanden sind.

2024-12-03 15:16 UTC, bwhdien requested changes

2024-12-03 15:16 UTC, bwhdien commented on docs/praxisleitfaden/semantik.md
> +    "metadata": {
Hatten wir metadata als Attribut?

2024-12-03 15:16 UTC, bwhdien commented on docs/praxisleitfaden/semantik.md
> +                "partOf": "IRI-der-Gruppe-oder-der-Schule"
Besser urn:schulconnex..... = UUID der Gruppe

2024-12-03 15:16 UTC, bwhdien commented on docs/praxisleitfaden/semantik.md
> +                    "key": "usageCount",
JSON und JSON-LD sind hier nicht gleich

2024-12-05 17:26 UTC, bwhdien approved these changes

2024-12-09 10:20 UTC, TheAnhNguyenFOKUSFAME commented
@bwhdien Bitte in den Lizenzen Branch reinmergen.

2024-12-09 10:41 UTC, merged