#240 Rechtschreibfehler korrigieren (Review und Polishing)
Schulconnex/Schulconnex pull request #278
Opened 2024-12-19 08:41 UTC by gorkemg

Mehrere kleine Korrekturen. 

- Einheitliche Benutzung von "Website", statt "Webseite"
- Benutzung von "sodass" statt "so dass" (beides korrekt, "sodass" wird vom Duden empfohlen)
- Doppelte Leerzeichen entfernt
- Genitiv vereinheitlicht ("Personenkontexts", "Löschzeitpunkts")

2024-12-19 16:38 UTC, bwhdien commented
@gorkemg Kann das reviewt werden?

2024-12-19 17:11 UTC, gorkemg commented
Ja gerne. Mehr habe ich zunächst nicht gefunden.

2024-12-19 17:16 UTC, bwhdien requested changes

2024-12-19 17:16 UTC, bwhdien commented on docs/footer/impressum.md
> +Unser Angebot enthält Links zu externen Websiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der v
Besser Websites, scheint mir

2024-12-20 07:04 UTC, gorkemg commented on docs/footer/impressum.md
> +Unser Angebot enthält Links zu externen Websiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der v
Habe ich korrigiert. Danke für den Hinweis.

2024-12-20 07:20 UTC, bwhdien approved these changes

2024-12-20 07:47 UTC, aldafu approved these changes
lgtm

2024-12-20 07:53 UTC, merged