239 - Sprache Polishing
Schulconnex/Schulconnex pull request #280
Opened 2024-12-23 10:50 UTC by ChristianFuhrhop

- Kleinere Satzanpassungen
- Hinzufügung 'Laufzeit' zu Datenmodellen bei Diensten Entfernung kleinerer JSON-Beispiele bei einfachen Datentypen (Genauere und aktueller JSON-Beispiele sind im OpenAPI Teil der Spezifikation.) 
- Entfernung der Diente- und Quellsystem-spezifischen allgemeinen Beschreibungen aus dem gemeinsamen "Allgemein"-Teil.
- Anpassung Gendervarianten bei Organisationsadministrator/in und Systemadministrator/in 
- Entfernung Validierung aus Dienste-Sidebar.

2024-12-27 10:26 UTC, bwhdien requested changes

2024-12-27 10:26 UTC, bwhdien commented on docs/allgemeines.md
> -<AllgemeinesDienste />
Warum sind die inkludierten Texte entfernt worden?

2024-12-27 10:26 UTC, bwhdien commented on docs/schnittstellendefinition/schnittstellendefinition.md
> +`POST` wird oft benutzt, um mehrere Daten gleichzeitig zu senden und
"beziehungsweise" muss weg?

2024-12-27 12:09 UTC, ChristianFuhrhop commented on docs/allgemeines.md
> -<AllgemeinesDienste />
Weil die in "Allgemeines" (was für beide Teile der Spezifikation gilt) nichts zu suchen haben. Und weil die beiden spezifischen Teile schon in den entsprechenden Abschnitten für  Dienste und Quellsysteme inkludiert sind.
Hier im gemeinsamen Teil sind sie daher fehl am Platze.

2024-12-30 13:45 UTC, bwhdien requested changes
Ein Korrektur ist noch notwendig. 

GGf. könnte auch eine KI noch einmal Vorschläge zur Vereinfachung der Formulierungen machen.

2024-12-30 13:45 UTC, bwhdien commented on src/openapi/paths-gruppen-id-gruppenzugehoerigkeiten.yaml
> +    Eine mehrfache Nutzung des gleichen Filters in einer Anfrage ist darf nicht erfolgen. Entsprechen keine
"ist" muss weg.
Oder "Jeder Filter darf in ein und derselben Anfrage nur einmal benutzt werden."

2024-12-30 13:45 UTC, bwhdien commented on src/openapi/paths-gruppen.yaml
> +    Eine mehrfache Nutzung des gleichen Filters in einer Anfrage darf nicht erfolgen. Entsprechen keine Werte
S. Kommentar oben

2024-12-30 16:46 UTC, ChristianFuhrhop commented on src/openapi/paths-gruppen-id-gruppenzugehoerigkeiten.yaml
> +    Eine mehrfache Nutzung des gleichen Filters in einer Anfrage ist darf nicht erfolgen. Entsprechen keine
Repariert.

2024-12-30 16:49 UTC, ChristianFuhrhop commented on src/openapi/paths-gruppen.yaml
> +    Eine mehrfache Nutzung des gleichen Filters in einer Anfrage darf nicht erfolgen. Entsprechen keine Werte
Hier sehe ich den Fehler nicht. Anders als bei der Version in 'paths-gruppen-id-gruppenzugehoerigkeiten.yaml' ist hier kein überzähliges 'ist' aus der Vorversion vorhanden. (Oder bezieht sich das "S. Kommentar oben" auf eine potentielle KI Umformulierung?)

2024-12-31 09:46 UTC, bwhdien commented on src/openapi/paths-gruppen.yaml
> +    Eine mehrfache Nutzung des gleichen Filters in einer Anfrage darf nicht erfolgen. Entsprechen keine Werte
Ja, wohl eher KI

2024-12-31 09:47 UTC, bwhdien approved these changes

2025-01-12 16:43 UTC, bwhdien approved these changes

2025-01-12 16:43 UTC, merged